import "./globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={inter.className}>
        <nav className="flex justify-between bg-blue-500 p-4 border-b-2 shadow-xl">
          <div className="flex">
            <p className=" border-t-2 border-b-2 border-l-white  text-white  text-4xl font-semibold  py-2 shadow-xl">
              English Steps
            </p>
          </div>

          <ul className="flex space-x-6 items-center">
            <Image
              className="inline"
              src="/mascot2.png"
              alt="me"
              width="70"
              height="50"
            />
            <li className=" text-white">
              <Link href="/">Home</Link>
            </li>
            <li className=" text-white">
              <Link href="/price">Price</Link>
            </li>
            <li className=" text-white">
              <Link href="about">About</Link>
            </li>

            <li className="text-white">
              <a>Applicaton</a>
            </li>
            <li className="bg-orange-500 p-3 rounded shadow border-gray-100 font-semibold text-white hover:mb-1">
              <Link href="signUp">Free trial</Link>
            </li>
          </ul>
        </nav>
        {children}
        <hr className="w-48 h-1 mx-auto my-4 bg-gray-100 border-0 rounded md:my-10 dark:bg-gray-700" />
        <div>
          <h1 className="text-4xl font-bold text-neutral-700 m-8 text-center">
            <p className="mb-2">Contact:</p>
            ☎: 08078349350 <p>✉: englishsteps20@gmail.com</p>
          </h1>
        </div>
      </body>
    </html>
  );
}
